version: '3.1'

services:
  monerod:
    build: daemon
    restart: always
    ports:
      - 18080:18080
      - 18081:18081
    environment:
      P2P_PORT: 18080
      RPC_PORT: 18081
    volumes:
      - ./.monero:/home/monerod
  
  miner:
    build: miner
    restart: always
    deploy:
      mode: replicated
      replicas: 2

