# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer:4.7.3
    restart: always
    ports:
      - 8080:8080
