FROM public.ecr.aws/lambda/python:3.9

# Need to have GCC to have certain things install correctly
RUN yum group install "Development Tools" -y

COPY requirements.txt /tmp/requirements.txt

RUN pip3 install -r /tmp/requirements.txt

# This evn var comes preset in this container image
COPY app/*.py "${LAMBDA_TASK_ROOT}"/

# The AWS Lambda entrypoint is already set such that as long as the CMD
# argument is provided pointing to the lambda handler then it will work
CMD [ "main.handler" ]
