version: '3.7'

services:

  db:
    image: romanmc72/flask-db:0.0.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.3
    restart: always
    ports:
      - 9000:8080
